"""s4_evaluate pipeline — runs inference -> metrics -> export.

Standalone usage:
    uv run python -m src.s4_evaluate.pipeline
"""

from __future__ import annotations

from pathlib import Path

import structlog

from src.config import S4Config
from src.constants import S3_OUTPUT, S4_OUTPUT, SPLIT_DATASET
from src.s4_evaluate.export import export_results
from src.s4_evaluate.inference import run_inference
from src.s4_evaluate.metrics import compute_metrics

logger = structlog.get_logger(__name__)


def run_pipeline(config: S4Config | None = None) -> None:
    """Evaluate all trained models on the test set.

    Assumes COCO JSON annotations already exist (generated by s1_prepare).

    Flow:
        1. Run inference with trained model.
        2. Compute COCO metrics.
        3. Export results to JSON.

    Args:
        config: Section configuration. Uses defaults when ``None``.
    """
    config = config or S4Config()

    logger.info("s4_pipeline_start")

    test_dir = Path(config.eval.data_dir) if config.eval.data_dir else (SPLIT_DATASET / "test")

    gt_path = test_dir / "_annotations.coco.json"
    if not gt_path.exists():
        logger.error("s4_missing_coco_annotations", path=str(gt_path))
        raise FileNotFoundError(
            f"COCO annotations not found: {gt_path}. Run s1_prepare first (includes YOLO→COCO conversion)."
        )

    model_path = Path(config.eval.model_path) if config.eval.model_path else (S3_OUTPUT / "rf_detr")
    pred_path = S4_OUTPUT / "predictions.json"
    predictions = run_inference(
        model_path=model_path,
        data_dir=test_dir,
        output_path=pred_path,
        device=config.eval.device,
        conf_threshold=config.eval.conf_threshold,
    )

    metrics_path = S4_OUTPUT / "metrics.json"
    metrics = compute_metrics(
        predictions=config.eval.predictions or pred_path,
        ground_truth=config.eval.ground_truth or gt_path,
        iou_threshold=config.eval.iou_threshold,
        output_path=metrics_path,
    )

    results_path = S4_OUTPUT / "results.json"
    export_results(
        results=metrics if isinstance(metrics, dict) else predictions,
        output_path=results_path,
    )

    logger.info("s4_pipeline_complete")


if __name__ == "__main__":
    from src.cli_helpers import standalone_main

    standalone_main(
        config_model=S4Config,
        run_fn=run_pipeline,
        description="s4_evaluate pipeline",
        skip_fields=["eval"],
    )
